"""Precompute the TSN-ready TV-L1 Flow input for every selected LAV-DF video.

This is a CPU-only preprocessing stage.  It uses exactly the temporal grid,
six-frame TV-L1 windows, centre crop, resize and Flow normalisation used by
``UniCaCLF.extract_unicaclf_offline_features``.  The resulting cache contains
one ``float16`` array per video::

    <output-root>/<split>/<video_id>.npy   # [T, 10, image_size, image_size]

``T`` is the number of positions generated by ``video_stride_frames``.  The
stored tensor is already normalised with ``(flow - 128) / 128`` and can be
passed directly to the TSN-Flow encoder after loading it as float32.

The script does *not* use a GPU.  To process videos concurrently on one
machine, use torchrun only as a process launcher; each rank receives a
disjoint ``records[rank::world_size]`` shard and creates different files:

    torchrun --standalone --nproc_per_node=8 -m flow_preprocess.precompute_tvl1_flow ...

There is deliberately no per-video ``try/except``: a bad MP4, missing TV-L1
module, or write error stops the job with a full traceback.  This is important
because a partial Flow cache must not silently be treated as complete.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import numpy as np
import torch
from decord import VideoReader, cpu
from tqdm import tqdm

from UniCaCLF.probe_tsn_neurons import FLOW_MEAN, FLOW_STD, _dense_flow, resize_crop


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lavdf-root", type=Path, required=True)
    parser.add_argument("--subset", type=Path, required=True,
                        help="The fixed LAV-DF subset JSON, e.g. lavdf_18k.json")
    parser.add_argument("--output-root", type=Path, required=True,
                        help="Directory that will contain <split>/<video_id>.npy")
    parser.add_argument("--splits", nargs="+", default=["train", "dev", "test"])
    parser.add_argument("--video-stride-frames", type=int, default=4)
    parser.add_argument("--image-size", type=int, default=256)
    parser.add_argument("--flow-bound", type=float, default=20.0)
    parser.add_argument("--chunk-size", type=int, default=32,
                        help="Temporal Flow samples built at once; controls CPU RAM, not GPU batching")
    parser.add_argument("--decode-threads", type=int, default=2,
                        help="Decord threads per preprocessing process")
    parser.add_argument("--cache-dtype", choices=("float16", "float32"), default="float16")
    parser.add_argument("--max-items", type=int, default=None,
                        help="Debug limit per split, applied globally before rank sharding")
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def rank_and_world_size() -> tuple[int, int]:
    """Read torchrun environment variables without initialising CUDA/NCCL."""
    rank = int(os.environ.get("RANK", "0"))
    world_size = int(os.environ.get("WORLD_SIZE", "1"))
    local_rank = int(os.environ.get("LOCAL_RANK", "0"))
    if not (0 <= rank < world_size and 0 <= local_rank < world_size):
        raise RuntimeError(f"Invalid distributed environment: rank={rank}, local_rank={local_rank}, world_size={world_size}")
    return rank, world_size


def video_grid(path: Path, stride: int, decode_threads: int) -> tuple[np.ndarray, float]:
    reader = VideoReader(str(path), ctx=cpu(0), num_threads=decode_threads)
    frame_count = len(reader)
    fps = float(reader.get_avg_fps())
    if frame_count < 1 or fps <= 0:
        raise ValueError(f"Unreadable video: {path}")
    centres = np.arange(0, frame_count, stride, dtype=np.int64)
    return centres.astype(np.float64) / fps, frame_count / fps


def flow_chunk(reader: VideoReader, times: np.ndarray, image_size: int, flow_bound: float) -> torch.Tensor:
    """Exact CPU equivalent of ``flow_input(..., period_start=0, period_end=duration)``."""
    fps = float(reader.get_avg_fps())
    frame_count = len(reader)
    centres = np.clip(np.rint(times * fps).astype(np.int64), 0, frame_count - 1)
    windows = [np.clip(np.arange(centre - 2, centre + 4), 0, frame_count - 1) for centre in centres]
    required = np.unique(np.concatenate(windows))
    decoded = reader.get_batch(required).asnumpy()
    frame_map = {int(index): frame for index, frame in zip(required, decoded)}
    samples: list[np.ndarray] = []
    for indices in windows:
        channels: list[np.ndarray] = []
        for left, right in zip(indices[:-1], indices[1:]):
            x, y = _dense_flow(frame_map[int(left)], frame_map[int(right)], "tvl1", flow_bound)
            channels.extend((x, y))
        samples.append(np.stack(channels, axis=-1))
    value = resize_crop(np.stack(samples), image_size)
    return (value - FLOW_MEAN) / FLOW_STD


def main() -> None:
    args = parse_args()
    if args.video_stride_frames < 1 or args.image_size < 1 or args.chunk_size < 1 or args.decode_threads < 1:
        raise ValueError("--video-stride-frames, --image-size, --chunk-size and --decode-threads must be positive")
    rank, world_size = rank_and_world_size()
    records = json.loads(args.subset.read_text(encoding="utf-8"))
    settings = {
        "method": "tvl1",
        "flow_bound": args.flow_bound,
        "video_stride_frames": args.video_stride_frames,
        "image_size": args.image_size,
        "stored_layout": "T,10,H,W",
        "stored_value": "(resize_crop(encoded_tvl1_flow) - 128) / 128",
        "cache_dtype": args.cache_dtype,
        "world_size": world_size,
    }
    if rank == 0:
        args.output_root.mkdir(parents=True, exist_ok=True)
        (args.output_root / "flow_cache_settings.json").write_text(json.dumps(settings, indent=2), encoding="utf-8")

    processed = 0
    for split in args.splits:
        split_records = [item for item in records if item.get("split") == split]
        if args.max_items is not None:
            split_records = split_records[:args.max_items]
        for item in tqdm(split_records[rank::world_size], desc=f"TV-L1 cache {split} rank {rank}", disable=rank != 0):
            source = args.lavdf_root / item["file"]
            times, _ = video_grid(source, args.video_stride_frames, args.decode_threads)
            # Use <output-root>/<metadata split>/<video id>.npy, rather than
            # source.parent, so the cache remains portable if LAV-DF moves.
            output = args.output_root / split / f"{source.stem}.npy"
            if output.is_file() and not args.overwrite:
                cached = np.load(output, mmap_mode="r")
                expected = (len(times), 10, args.image_size, args.image_size)
                if tuple(cached.shape) != expected:
                    raise ValueError(f"Existing cache has wrong shape: {output}: {cached.shape}, expected {expected}")
            else:
                output.parent.mkdir(parents=True, exist_ok=True)
                temporary = output.with_suffix(output.suffix + f".partial.{os.getpid()}")
                dtype = np.float16 if args.cache_dtype == "float16" else np.float32
                cache = np.lib.format.open_memmap(temporary, mode="w+", dtype=dtype,
                                                   shape=(len(times), 10, args.image_size, args.image_size))
                reader = VideoReader(str(source), ctx=cpu(0), num_threads=args.decode_threads)
                for begin in range(0, len(times), args.chunk_size):
                    value = flow_chunk(reader, times[begin:begin + args.chunk_size], args.image_size, args.flow_bound)
                    cache[begin:begin + len(value)] = value.numpy().astype(dtype, copy=False)
                cache.flush()
                del cache
                temporary.replace(output)
            processed += 1
    print(f"rank {rank}/{world_size}: cached {processed} videos under {args.output_root}")


if __name__ == "__main__":
    main()
